# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage/WebP'#, '~> 4.4.8'
  pod 'MRProgress'#, '~> 0.8.3'

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUITests' do
    # Pods for testing
  end

end
